try{document.domain=window.location.host.substring(window.location.host.indexOf(".")+1)}catch(e$$8){}var $=function(a){return document.getElementById(a)};String.prototype.truncate_cn=function(a,b){return this.length<=a?this:this.substring(0,a)+(b||"..")};String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")};String.prototype.escapeHTML=function(){return this.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\ /g,"&nbsp;")};
String.prototype.addslashes=function(){return this.replace(/([\\"'])/g,"\\$1").replace(/[\n\r]/g,"\\n")};
function jsLoader(a,b,d){if("undefined"==typeof d||null==d)d="jsonstring";var e="var_"+(new Date).getTime().toString().substring(7)+parseInt(1E4*Math.random()),a=a+((-1==a.indexOf("?")?"?":"")+"&v="+e),f=document.createElement("script");f.setAttribute("type","text/javascript");f.setAttribute("src",a);var g=document.getElementsByTagName("head")[0];f.onload=f.onreadystatechange=function(){if(!f.readyState||"loaded"==f.readyState||"complete"==f.readyState)if(!("undefined"==typeof window[e]||null==window[e])){if("jsonstring"==
d){var a=eval("("+window[e]+")");"function"==typeof b&&b(a)}else"function"==typeof b&&b(window[e]);try{g.removeChild(f)}catch(l){}e=f=null}};g.appendChild(f)}function addListener(a,b,d){a&&(a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent("on"+b,d))}function getEventTarget(a){a=a||window.event;return a.srcElement||a.target}function stopBubble(a){a=a||window.event;a.preventDefault?(a.preventDefault(),a.stopPropagation()):(a.cancelBubble=!0,a.returnValue=!1)}
function isAncestor(a,b){if(!b||!a)return!1;for(;b!==a&&b!=document.body;)b=b.parentNode;return b===a}function haveClass(a,b){return!a?!1:"undefined"!=typeof a.className&&a.className.match(RegExp("(\\s|^)"+b+"(\\s|$)"))}function addClass(a,b){if(!(null==a||"undefined"==typeof a)&&!haveClass(a,b))a.className=a.className?a.className+(" "+b):b}function removeClass(a,b){haveClass(a,b)&&(a.className=a.className.replace(RegExp("(\\s|^)"+b+"(\\s|$)"),"").trim())}
function replaceClass(a,b,d){haveClass(a,b)&&(removeClass(a,b),addClass(a,d))}function get_url_para(a){for(var b=(0<location.search.length?location.search.substring(1):"").split("&"),d,e=0;e<b.length;++e)if(d=b[e].split("="),a==decodeURIComponent(d[0]).toLowerCase())return decodeURIComponent(d[1]);return""}
function readGet(){var a=window.location.href.replace(/&amp;/g,"&").replace(/\#.*$/,""),b={},d;if(-1<a.indexOf("?"))uriArr=a.split("?"),paraStr=uriArr[1];else return b;for(var a=-1<paraStr.indexOf("&")?paraStr.split("&"):Array(paraStr),e=0;e<a.length;e++)try{a[e]=-1<a[e].indexOf("=")?a[e]:a[e]+"=",d=a[e].split("="),b[d[0]]=decodeURIComponent(d[1].replace(/\+/g," "))}catch(f){}return b}var util={};util.readGet=readGet;util.jsLoader=jsLoader;
function gotoHelp(){window.open("/sethelp")}function setHomepage(a){if(document.all)try{document.body.style.behavior="url(#default#homepage)",document.body.setHomePage(a)}catch(b){gotoHelp()}else gotoHelp()}function addAsFavorite(a,b){st_get(this,"u01.func.addfav",0);try{if(window.sidebar)window.sidebar.addPanel(a,b,"");else if(document.all)window.external.AddFavorite(b,a);else return gotoHelp(),!0}catch(d){gotoHelp()}}
function pr_getdt1(a,b,d,e){var f=document,g="-",j=(new Date).getUTCMilliseconds(),l=f.cookie.match(/suid=([^;]*)(;|$)/);l?g=l[1]:(f.cookie="suid="+Math.round(2147483647*Math.random())*j%1E10+";path=/; domain=soso.com;expires=Sun, 18 Jan 2038 00:00:00 GMT;",(l=f.cookie.match(/suid=([^;]*)(;|$)/))&&(g=l[1]));e=e||"";(new Image(1,1)).src="http://pr.soso.com/pingd?srctype=getsret&ourl="+escape(a)+"&lurl="+escape(f.location)+"&suid="+g+"&ch="+b+"&sort="+d+"&sc="+e+"&rand="+Math.random()}
function pr_get(a,b,d,e){0==a.length||0==b.length||pr_getdt1(a,b,d,e)}function st_get(a,b,d){g_Get&&"u01"!=g_Get.cid&&b.replace(/^u01\./,"u01."+g_Get.cid);setTimeout(function(){"object"==typeof __sosostat&&"function"==typeof __sosostat.prget&&__sosostat.prget(a,b.trim()+"."+d,0,"daoh")},0)}
function installStat(){for(var a=document.body.getElementsByTagName("*"),b=a.length,d=0;d<b;++d){var e=a[d].getAttribute("st_get");e&&function(b){addListener(a[d],"click",function(){st_get(this,b,0)})}(e);if(e=a[d].getAttribute("st_get_group"))for(var f=a[d].getElementsByTagName("a"),g=0;g<f.length;++g)(function(a,b){addListener(f[g],"click",function(){st_get(this,a,b)})})(e,g)}}
Function.prototype.bind||(Function.prototype.bind=function(a){var b=this,d=Array.prototype.slice.call(arguments,1);return function(){var e=Array.prototype.slice.call(arguments);return b.apply(a,d.concat(e))}});function findUpTag(a,b){if(!a||!b)return null;for(b=b.toUpperCase();a&&a.tagName!=b;)a=a.parentNode;return a}function findDownTags(a,b){var d=[];if(!a||!b)return d;for(var e=a.firstChild,b=b.toUpperCase();e;){e.nodeType==1&&e.tagName==b&&d.push(e);e=e.nextSibling}return d}
function TopBar(a){a||(a={});var b=a.container||$("topWrap");b.appendChild(function(){var a=document.createElement("div");addClass(a,"fl");for(var b=[{text:"实用查询",href:"/chaxun.html"},{text:"电影",href:"/movie.html"},{text:"电视剧",href:"/tv.html"},{text:"团购",href:"/tuan.html"},{text:"游戏",href:"/youxi.html"},{text:"彩票",href:"/caipiao.html"}],f=["<a class='setIndex' href='javascript:;' target='_self'><span class='icon'></span><span>设为主页</span></a><span class='line'></span>"],
g=0;g<b.length;++g)f.push("<a href='{$href}'>{$text}</a>".replace("{$href}",b[g].href).replace("{$text}",b[g].text));a.innerHTML=f.join("");addListener(a,"click",function(b){var e=getEventTarget(b);if(e.tagName=="SPAN"||haveClass(e,"setIndex")){stopBubble(b);st_get(e,"dh.leftsethome",0);setHomepage(location.protocol+"//"+location.host)}else if(e.tagName=="A")if(b=a.getElementsByTagName("a"))for(var f=0;f<b.length;++f)if(b[f]===e)return st_get(e,"dh.topleft",f)});return a}());this.show=function(a){if(a){addClass(a,
"fr");b.appendChild(a)}}}
function Cookie(){this.get=function(a){return(a=document.cookie.match(RegExp("(^| )"+a+"=([^;]*)(;|$)")))?unescape(a[2]):null};this.getNotExpireTime=function(){var a=new Date;a.setTime(a.getTime()+31536E6);return a.toGMTString()};this.set=function(a,b,d,e,f){document.cookie=a+"="+escape(b)+"; expires="+(d?d:this.getNotExpireTime())+";path="+(e?e:"/")+"; domain=."+(f?f:window.location.host)};this.del=function(a,b,d){d=d||document.domain;document.cookie=a+"=;path="+(b?b:"/")+";domain="+d+";expires="+
(new Date("1970/1/1")).toGMTString()}}function cookie_set(a,b,d){if(d=="long"){d=new Date;d.setTime(d.getTime()+31536E7);d=d.toUTCString()}else typeof d=="object"&&(d=d.toUTCString());document.cookie=a+"="+b+(d?"; expires="+d:"")}function cookie_get(a){var b=null;if(document.cookie&&document.cookie!="")for(var d=document.cookie.split(";"),e=0;e<d.length;e++){var f=d[e].trim();if(f.substring(0,a.length+1)==a+"="){b=decodeURIComponent(f.substring(a.length+1));break}}return b}
function cookie_del(a){cookie_set(a,null,new Date(1970,1,1))}
Storage=function(){var a,b,d;if(typeof window.localStorage=="object"){var e=window.localStorage;a=function(a){return e.getItem(a)};b=function(a,b){e.setItem(a,b)};d=function(a){e.removeItem(a)}}else if(document.body.addBehavior){var f=document.body,g=function(){try{f.load("faxin")}catch(a){}},j=function(){try{f.save("faxin")}catch(a){}};f.addBehavior("#default#userData");a=function(a){g();return f.getAttribute(a)};b=function(a,b){g();f.setAttribute(a,b);j()};d=function(a){g();f.removeAttribute(a);
j()}}if(!d){a=function(a){return cookie_get(a)};b=function(a,b){cookie_set(a,b)};d=function(a){cookie_del(a)}}return{get:a,set:b,del:d}}();
function History(a,b){if(!a)throw'[History] "key" must be set.\n';b||(maxLen=10);var d=function(b){if(typeof JSON!=="undefined"&&"stringify"in JSON)b=JSON.stringify(b);else{for(var d=[],g=0,j=b.length;g<j;g++)d.push('"'+b[g].addslashes()+'"');b="(["+d.join(",")+"])"}Storage.set(a,b)};this.getAll=function(){var b=Storage.get(a);try{return b?eval(b):[]}catch(d){return[]}};this.add=function(a){for(var f=this.getAll(),g=0,j=f.length;g<j;g++)if(f[g]==a){if(g==0)return;f=[].concat(f.slice(0,g),f.slice(g+
1));break}f.unshift(a);f.length>b&&(f=f.slice(0,b));d(f)};this.del=function(a){var b=this.getAll();if(b.length)for(var g=0,j=b.length;g<j;g++)if(b[g]==a){d([].concat(b.slice(0,g),b.slice(g+1)));break}};this.clear=function(){Storage.del(a)}}
function Observable(){var a={};this.addEventListener=function(b,d){if(typeof d!="function")return false;typeof a[b]=="undefined"&&(a[b]=[]);for(var e=0;e<a[b].length;++e)if(a[b][e]==d)return false;a[b].push(d);return true};this.removeEventListener=function(b,d){if(typeof a[b]=="undefined")return false;for(var e=0;e<a[b].length;++e)if(a[b][e]==d){a[b].splice(e,1);return true}return false};this.notify=function(b,d){if(a[b])for(var e=0;e<a[b].length;++e)if(typeof a[b][e]=="function")a[b][e](d)}}
(function(a,b,d){function e(){g(F);g(L);v=w.get("uin");x=w.get("luin");C=w.get("skey");D=w.get("lskey");v&&(v=v.replace(/^o0*/,""));x&&(x=x.replace(/^o0*/,""));v=v?v:"";y("uin",v);C=C?C:"";y("skey",C);x=x?x:"";y("luin",x);D=D?D:"";y("lskey",D);s(I+"navedSite.php?"+t[o]("&"))}function f(){g(M);if(!N){F&&(F.style.display="block");$("noLoginQQ").innerHTML=p}}function g(a){if(a)a.style.display="none"}function j(b){var d=b.expireat;typeof z=="function"&&z(b);b.daily||J(b.r,function(){y("x",A(b.r))("y",
A(b.s))("hs",a[n])("ss",a[r]);s(I+"navi.php?callback=avFinishCallback&"+t[o]("&"));w.set(K,1,d)})}function l(a){a&&typeof G=="function"&&G(a)}function m(a){for(var b=[],d=(1<<B)-1,e=0,f=a.length;e<f*B;e=e+B)b[e>>5]=b[e>>5]|(a.charCodeAt(e/B)&d)<<e%32;return b}function h(a){for(var b=q?"0123456789ABCDEF":"0123456789abcdef",d="",e=0,f=a.length;e<f*4;e++)d=d+(b.charAt(a[e>>2]>>e%4*8+4&15)+b.charAt(a[e>>2]>>e%4*8&15));return d}var p=util.readGet().uin,n="haosign",r="sososign",t=[],u={},q=0,o="join",s=
util.jsLoader,A=encodeURIComponent,H=Math,E=cd="concat",B=8,y=function(a,b){return a in u?y:(u[a]=true,t=t[E](a[cd]("=",b)),y)},z,G,w=new Cookie,K="navedDaily",I="http://faxin.soso.com/",M=$("tipLogin"),F=$("tipNoLogin"),L=$("tipErrQQ"),N=w.get(K),v=w.get("uin"),C=w.get("skey"),x=w.get("luin"),D=w.get("lskey"),J=function(b,d){if(!a[n])return setTimeout(function(){J(b,d)},50),false;var e=v||x;a[r]=h(m(A(a.__nick||"nologin")+"|"+e+"|"+b)).split("").reverse()[o]("");d()};a[b]=function(g,h){return z=
g,G=h,a[b+"FinishCallback"]=l,a[b+"Callback"]=j,d.onmousemove=function(b){var b=b||event,e=[],f=v||x;d.onmousemove=null;for(var b=m([A(a.__nick||"nologin"),b.type,b.pageX||b.clientX,f,b.pageY||b.clientY][o]("|")),f=[],g=0,h=b.length;g<h;g++)e[g]=g;e.sort(function(){return H.random()*5-1});f.push(e[o]("_"));for(g=0;g<h;g++)f.push(b[e[g]]);a[n]=f[o](",")},{login:e,nologin:f}}})(window,"av",document);
function installHint(a,b,d,e){if(a&&b){e=e||"onfocus";a.hintWording=b;a.onfocus=this.onfocus.bind(a,e);a.onblur=this.onblur.bind(a,d,e)}}installHint.prototype.onfocus=function(a){this.onfocus=null;if(!haveClass(this,a))this.value="";addClass(this,a);typeof callback=="function"&&callback();if(this.blurtmo){clearTimeout(this.blurtmo);this.blurtmo=null}};
installHint.prototype.onblur=function(a,b){this.onfocus=installHint.prototype.onfocus.bind(this,b);if(this.value=="")if(a)this.blurtmo=setTimeout(function(){this.value=this.hintWording;removeClass(this,b)}.bind(this),a);else{this.value=this.hintWording;removeClass(this,b)}};
function UserModel(){this.isLogined=false;this.face=1;this.golds=0;this.isLogin=function(){return this.isLogined};this.getFaceImgUrl=function(){var a=parseInt(this.face),a=parseInt((a+3)/3);if(a<1||a>180)a=1;return"http://cache.soso.com/img/i/faces/u"+a+".gif"};this.getNick=function(){return this.nick||""}}
function UserController(a){function b(){n.set(u,e(s))}function d(){var a=n.get(u),b={};if(typeof a=="string")for(var a=a.split("|"),d=0;d<a.length;++d){var e=a[d].split("=");e.length==2&&(b[e[0]]=e[1])}for(k in s)typeof b[k]!="undefined"&&(s[k]=b[k])}function e(a){var b=[];for(k in a)b.push(k+"="+a[k]);return b.join("|")}function f(a,b){if(a!==false){window.g_user=q;q.isLogined=true;for(k in a)q[k]=a[k]}typeof b==="function"&&b(q)}function g(a){try{if(a&&a.gold&&o){q.golds=parseInt(q.golds)+parseInt(a.gold);
o.showItemTip("golds","金币("+q.golds+")")}}catch(b){}}function j(a){if(!(n.get("skey")&&n.get("uin")||n.get("lskey")&&n.get("luin"))){st_get(null,"dh.nologin",0);return f(false,a)}if(typeof av=="function"){st_get(null,"dh.getinfostart",0);avObj=av(function(b){st_get(null,"dh.getinfoend",0);f(b,a)},g);avObj.login()}}function l(a){if(a.isLogin()){r.show(o.createLoginView(a));o.showItemTip("golds","金币("+a.golds+")");h(p)}else r.show(o.createUnLoginView())}function m(a){function b(a){a=parseInt(a);return isNaN(a)?
0:a}if(o){for(var d=["weibo","qzone","qqmail"],e=0;e<d.length;++e)if(a[d[e]]&&a[d[e]].data)a[d[e]].data.number=0;try{a.weibo.data.number=a.weibo.data.number+b(a.weibo.data.create);a.weibo.data.number=a.weibo.data.number+b(a.weibo.data.fans);a.weibo.data.number=a.weibo.data.number+b(a.weibo.data.home);a.weibo.data.number=a.weibo.data.number+b(a.weibo.data.mentions);a.weibo.data.number=a.weibo.data.number+b(a.weibo.data["private"]);a.qqmail.data.number=b(a.qqmail.data.unreadcount);a.qzone.data.number=
0;if(a.qzone&&a.qzone.data){a.qzone.data.number=b(a.qzone.data.initnum);a.qzone.data.number=a.qzone.data.number+b(a.qzone.data.aboutnum);a.qzone.data.number=a.qzone.data.number+b(a.qzone.data.passivenum)}}catch(f){}for(e=0;e<d.length;++e){var g=a[d[e]].data;if(g){g.number=b(g.number);try{o.showItemTip(d[e],g.number>99?"99+":g.number!=0?g.number:"",g.number!=0&&g.number!=s[d[e]+"num"])}catch(h){}q[d[e]]=g}}}}function h(a){var b="getUnreadNumber"+parseInt(Math.random()*1E6);window[b]=function(d){m(d,
a);window[b]=null};jsLoader("http://sou.qq.com/online/getunreadnum.php?func="+b)}function p(){}var n=a.cookie,r=new TopBar,t=new Ptlogin2,u="txtips",q=new UserModel,o=null,s={nologintip:false,qqmailnum:0,weibonum:0,qzonenum:0};this.loadBasicInfo=function(){j(l)};(function(){d();o=new UserView({nologintip:s.nologintip});o.addEventListener("click_exit",function(){for(var a=["uin","skey","luin","lskey","__nick","__face"],b=0;b<a.length;++b)n.del(a[b]);location.href=location.href;st_get(null,"dh.click_exit",
0)});o.addEventListener("close_tip",function(){s.nologintip=1;b();st_get(null,"dh.close_tip",0)});o.addEventListener("click_login",function(){s.nologintip=1;b();t.open();st_get(null,"dh.click_login",0)});o.addEventListener("click_item",function(a){if(typeof s[a+"num"]!="undefined"&&typeof q[a]!="undefined")s[a+"num"]=q[a].number;b();st_get(null,"dh.item."+a,0)})})()}
function UserView(a){function b(a){return a==0?"":a>p?"99+":a}function d(){var a=document.createElement("span");addClass(a,"line");return a}function e(a,b){var d=document.createElement("a");addClass(d,"user");d.innerHTML="<img class='avatar' src='${avatar}' alt=''/ ><span class='name'>${usernick}</span>".replace("${avatar}",a).replace("${usernick}",b.truncate_cn(12).escapeHTML());d.href="http://soso.qq.com/q?bid=303";return d}function f(a){var b=document.createElement("a"),d=document.createElement("span"),
e=document.createElement("span");a.className&&addClass(b,a.className);addClass(d,"icon");addClass(e,"num");if(a.has_tip){var f=document.createElement("span");addClass(f,"tip hidden");d.appendChild(f)}b.appendChild(d);b.appendChild(e);if(a.menu_config){var g=null;addListener(b,"mouseover",function(d){stopBubble(d);g||(g=new Menu(a.menu_config));g.showAt(b.getBoundingClientRect().top+35,b.getBoundingClientRect().left+10)});addListener(b,"mouseout",function(a){var a=a.relatedTarget||a.toElement,d;if(d=
a){for(;a&&a!=b&&a!=document.body;)a=a.parentNode;d=a==b}d||g&&g.hidden()});addListener(b,"click",function(){g&&g.hidden()})}if(a.href)b.href=a.href;return b}function g(a){var b=100;a.style.zoom=1;var d=setInterval(function(){b=b-5;a.style.opacity=parseFloat(b/100);a.style.filter=" alpha(opacity = "+b+");";if(b<=0){clearTimeout(d);addClass(a,"nodisplay")}},15)}function j(){var a=document.createElement("a");a.innerHTML="退出";a.href="#";addListener(a,"click",function(a){stopBubble(a);l.notify("click_exit")});
return a}var l=new Observable,m=null,h=null,p=99,n={qzone:{className:"qZone",has_tip:true,dom:null,href:"http://qzone.qq.com",menu_config:{title:"QQ空间",items:[{html:function(){return!h||!h.qzone||!(h.qzone.initnum+h.qzone.passivenum)?"":"好友动态("+b(h.qzone.initnum+h.qzone.passivenum)+")"}},{html:function(){return!h||!h.qzone||!h.qzone.aboutnum?"":"与我有关("+b(h.qzone.aboutnum)+")"}}]}},weibo:{dom:null,menu:null,has_tip:true,href:"http://t.qq.com",className:"twitter",menu_config:{title:"腾讯微博",items:[{html:function(){return!h||
!h.weibo||!h.weibo.home?"":"未读消息("+b(h.weibo.home)+")"}},{html:function(){return!h||!h.weibo||!h.weibo["private"]?"":"未读私信("+b(h.weibo["private"])+")"}},{html:function(){return!h||!h.weibo||!h.weibo.fans?"":"新增听众("+b(h.weibo.fans)+")"}},{html:function(){return!h||!h.weibo||!h.weibo.mentions?"":"提到我的("+b(h.weibo.mentions)+")"}},{html:function(){return!h||!h.weibo||!h.weibo.create?"":"首页广播("+b(h.weibo.create)+")"}}]}},qqmail:{dom:null,className:"mail",hasseperate:true,has_tip:true,href:"http://mail.qq.com",
menu_config:{title:"QQ邮箱",items:[{html:function(){return!h||!h.qqmail||!h.qqmail.unreadcount?"":"未读邮件("+b(h.qqmail.unreadcount)+")"}}]}},golds:{className:"gold",href:"http://soso.qq.com/q?bid=303&cid=dh.my.coin&ch=dh.my.coin&channel=naved",hasseperate:true}},r={},t=a.nologintip||false;this.createLoginView=function(a){if(!m){m=document.createElement("div");r=e(a.getFaceImgUrl(),a.getNick());m.appendChild(r);m.appendChild(d());for(k in n){n[k].dom=f(n[k]);n[k].dom&&m.appendChild(n[k].dom);(function(a,
b){addListener(b.dom,"click",function(){try{for(var d=b.dom.getElementsByTagName("span"),e=0;e<d.length;++e)if(haveClass(d[e],"tip")){addClass(d[e],"hidden");break}l.notify("click_item",a)}catch(f){}})})(k,n[k]);n[k].hasseperate&&m.appendChild(d())}m.appendChild(j())}h=a;return m};this.createUnLoginView=function(){var a=document.createElement("x");a.href="javascript:;";addListener(a,"click",function(a){stopBubble(a);try{l.notify("click_login")}catch(b){}d&&
addClass(d,"nodisplay")});var b=document.createElement("div");addClass(b,"login");b.appendChild(a);if(t)return b;var d=$("loginTip");if(!d)return b;removeClass(d,"nodisplay");addListener(d,"click",function(a){stopBubble(a);if((a=getEventTarget(a))&&a.tagName=="A")try{g(d);l.notify("close_tip")}catch(b){}});setTimeout(function(){g(d)},1E4);return b};this.showItemTip=function(a,b,d){if(a&&n[a].dom)for(var a=n[a].dom.getElementsByTagName("span"),e=0;e<a.length;++e){d&&haveClass(a[e],"tip")&&removeClass(a[e],
"hidden");if(haveClass(a[e],"num")&&b)a[e].innerHTML=b}};this.addEventListener=function(a,b){l.addEventListener(a,b)};this.removeEventListener=function(a,b){l.removeEventListener(a,b)}}
function PageMask(){var a=null;this.open=function(){if(a==null){a=document.createElement("div");addClass(a,"pageMask");document.body.appendChild(a)}a.style.width=document.body.clientWidth+"px";a.style.height=document.body.clientHeight+"px";a.style.display="block"};this.close=function(){a&&(a.style.display="none")}}
function Ptlogin2(){var a=null,b=null,d=null;window.ptlogin2_onResize=function(d,f){a.style.width=d+"px";a.style.height=f+"px";b.style.top=(document.documentElement.clientHeight-f)/2+"px";b.style.left=(document.documentElement.clientWidth-d)/2+"px"};window.ptlogin2_onClose=function(){addClass(b,"nodisplay");d&&d.close()};this.open=function(){if(!a){b=document.createElement("div");addClass(b,"loginDiv nodisplay");a=document.createElement("iframe");a.setAttribute("scrolling","no");a.setAttribute("frameBorder",
0);b.appendChild(a);document.body.appendChild(b);d=new PageMask}removeClass(b,"nodisplay");a.src="http://ui.ptlogin2."+document.domain+"/cgi-bin/login?appid=8000212&s_url="+encodeURIComponent(location.href)+"&f_url=loginerroralert&target=parent&link_target=blank&low_login=1&rd="+Math.random();d&&d.open()}}
function Menu(a){function b(){if(m){m.innerHTML="";for(var a=null,b=0;b<d.length;++b)if(a=f[b]){if(typeof d[b].html=="function")a.innerHTML=d[b].html();else if(typeof d[b].html=="string"&&d[b].html!="")a.innerHTML=d[b].html;a.innerHTML&&m.appendChild(a)}}}var d=a.items||[],e=a.title||"",f=[],g=null,j=null,l=null,m=null;this.showAt=function(a,b){l&&clearTimeout(l)&&(l=null);clearTimeout(j);j=setTimeout(function(){j=null;a&&(g.style.top=parseInt(a)+"px");b&&(g.style.left=parseInt(b)+"px");removeClass(g,
"hidden")},200)};this.hidden=function(){j&&clearTimeout(j)&&(j=null);clearTimeout(l);l=setTimeout(function(){l=null;addClass(g,"hidden")},0)};(function(){g=document.createElement("div");m=document.createElement("ul");addClass(g,"msgTip");for(var a=0;a<d.length;++a){var j=document.createElement("li");f.push(j)}b();a=document.createElement("span");addClass(a,"arrow");g.appendChild(a);if(e){a=document.createElement("h3");a.innerHTML=e;g.appendChild(a)}g.appendChild(m);addListener(g,"click",function(a){stopBubble(a)});
addClass(g,"hidden");document.body.appendChild(g)})()}function LinkModel(a,b,d){this.text=a||"";this.href=b||"";this.style=d||""}LinkModel.prototype.createElement=function(){var a=document.createElement("a");a.innerHTML=this.text;a.href=this.href;this.style&&(a.style.cssText=this.style);return a};
function SoSo_SmartBox(a,b,d){var e=this,f=typeof a=="object"?a:document.getElementById(a),g=false,j=-1,l=[],m=[],h="",p="",n=null,r=false,t=0,u=function(){for(pos in l)l[pos].className="mouseout"},q=function(a){return typeof a=="string"?a.replace(/^\s\s*/,"").replace(/\s\s*$/,""):""},o=q(f.value),s=function(){typeof b=="function"&&b()},A=function(){r=false;j=-1;l=[];m=[];h="";var a=typeof t=="object"?t:document.getElementById(t);a&&a!=null&&a.parentNode.removeChild(a)},H=function(){var a=document.createElement("div");
a.id=t="soso_SmartPop_"+Math.round(Math.random()*1E5);a.className="soso_SmartPop";a.style.height=""+m.length*26+"px";for(i in m){var b=document.createElement("div");b.style.height="26px";b.seq=parseInt(i);(function(){var a=b;e.Event.add(b,"mouseover",function(){u();a.className="mouseover";j=a.seq})})();(function(){e.Event.add(b,"mouseout",function(){u();j=-1})})();(function(){e.Event.add(b,"click",function(){o=p=f.value=m[j].word;s()})})();var d=document.createElement("div");d.innerHTML=m[i].word;
b.appendChild(d);a.appendChild(b);l.push(b)}return a},E="soso_jpcall_"+Math.round(1E6+Math.random()*1E7);window[E]=function(a){g=true;A();p=h=f.value;if(q(a)=="")a=false;else{a=a.split("\n");res=[];for(i=0;i<a.length;i++){a[i]=a[i].split("\t");res.push({word:a[i][1],hint:a[i][0],type:a[i][2]})}a=res}if(m=a){c=H();f.parentNode.appendChild(c);r=true}};var B=util.jsLoader,y=function(){if(haveClass(f,"onfocus")){soso_global_smartbox_data=[];g=false;var a="http://www.soso.com/smart.q?w="+encodeURIComponent(f.value)+
"&m="+E+"&_"+Math.random();B(a)}},z=function(){if(n!=null){clearTimeout(n);n=null}n=setTimeout(function(){!g||q(f.value).length==0?A():d()&&h!=f.value&&y();n=null},300)};(function(){e.Event.add(f,"keypress",function(a){if(!r&&(a.keyCode==38||a.keyCode==40)){g=true;z()}if(l.length!=0&&a.keyCode==13&&j!=-1){e.Event.stop(a);o=f.value;s()}});e.Event.add(f,"keyup",function(a){if(!r&&(a.keyCode==38||a.keyCode==40)){g=true;z()}if(l.length!=0)if(a.keyCode==13&&j!=-1){e.Event.stop(a);o=f.value;s()}else if(a.keyCode==
38){e.Event.stop(a);u();j=j<0?l.length-1:j-1;if(j==-1)h=f.value=p;else{l[j].className="mouseover";h=f.value=m[j].word}}else if(a.keyCode==40){e.Event.stop(a);u();j=j>l.length-1?0:j+1;if(j==l.length)h=f.value=p;else{l[j].className="mouseover";h=f.value=m[j].word}}else if(a.keyCode==27){e.Event.stop(a);u();A();f.value=p}});e.Event.add(f,"blur",function(){g=false;haveClass(f,"onfocus")&&z()});e.Event.add(window,"resize",function(){g&&y()});var a,b=function(){a=setTimeout(function(){if(o!=q(f.value)){o=
q(f.value);g=true;z()}a=setTimeout(arguments.callee,80)},80)};e.Event.add(f,"focus",function(){b()});e.Event.add(f,"blur",function(){clearTimeout(a)})})()}SoSo_SmartBox.prototype.Event={add:function(a,b,d){a.addEventListener?a.addEventListener(b,d,false):a.attachEvent("on"+b,d)},remove:function(a,b,d){a.removeEventListener?a.removeEventListener(b,d,false):a.detachEvent("on"+b,d)},stop:function(a){if(a.preventDefault){a.preventDefault();a.stopPropagation()}else{a.cancelBubble=true;a.returnValue=false}}};
function TabView(a){this.init(a);this.initEventsListener()}
TabView.prototype.init=function(a){this.config=a||{};this.container=a.container||null;this.currentClassName=a.currentClassName||"current";this.tabChangeType=a.tabChangeType&&a.tabChangeType=="hover"?"hover":"click";if(this.container){this.tabTagName=a.tabTagName||"li";this.currentIndex=0;this.onMouseEnterTab=typeof a.onMouseEnterTab=="function"?a.onMouseEnterTab:function(){};this.onMouseLeaveTab=typeof a.onMouseLeaveTab=="function"?a.onMouseLeaveTab:function(){};this.onClickTab=typeof a.onClickTab==
"function"?a.onClickTab:function(){};this.beforeChangeTab=typeof a.beforeChangeTab=="function"?a.beforeChangeTab:function(){};if(!(a.tabs instanceof Array))this.tabs=findDownTags(this.container,this.tabTagName);if(a.tabPanels instanceof Array)this.tabPanels=a.tabPanels}};
TabView.prototype.setCurrent=function(a){var b=this.tabs;if(b&&!(a<-1||a>=b.length)){for(var d=0;d<b.length;++d)d==a?addClass(b[d],this.currentClassName):removeClass(b[d],this.currentClassName);this.currentIndex=a;if(this.tabPanels&&!(!this.tabPanels instanceof Array))for(d=0;d<this.tabPanels.length;++d)d===a?removeClass(this.tabPanels[d],"nodisplay"):addClass(this.tabPanels[d],"nodisplay")}};
TabView.prototype.getTabIndex=function(a){var b=this.tabs;if(!a||!b)return-1;for(var d=0;d<b.length;++d)if(b[d]===a)return d;return-1};TabView.prototype.getCurrentIndex=function(){return this.currentIndex};
TabView.prototype.initEventsListener=function(){var a=this;addListener(this.container,"click",function(b){var d=getEventTarget(b),e=a.getTabIndex(findUpTag(d,a.tabTagName));a.onClickTab(e);if("click"==a.tabChangeType){stopBubble(b);e==-1||a.beforeChangeTab(e,d)===false||a.setCurrent(e)}});addListener(this.container,"mouseover",function(b){var d=getEventTarget(b),e=a.getTabIndex(findUpTag(d,a.tabTagName));if(e!=-1){a.onMouseEnterTab(e,d);if("hover"==a.tabChangeType){stopBubble(b);e==-1||a.beforeChangeTab(e)===
false||a.setCurrent(e)}}});addListener(this.container,"mouseout",function(b){var d=getEventTarget(b),e=a.getTabIndex(findUpTag(d,a.tabTagName));if(e!=-1){a.onMouseLeaveTab(e,d);if("hover"==a.tabChangeType&&e==a.getCurrentIndex()){stopBubble(b);a.setCurrent(-1)}}})};
(function(){function a(a){return(a.text?a.text:a.innerText)+f+a.href}function b(){addClass(h,"meUsecur");var e=g.getAll(),j=[];if(e.length){for(var l=0,m=e.length;l<m;l++){var n=e[l].split(f);j.push('<li><span><a href="'+n[1]+'" target="_blank">'+n[0]+'</a></span><em><a title="关闭" href="javascript:;">关闭</a></em></li>')}p.className="meUsedpop2";p.innerHTML="<ul>"+j.join("")+'</ul><p class="clearBtn"><a href="javascript:;">清空</a></p>'}else{p.className="meUsedpop1";p.innerHTML="暂无最近使用记录"}e=p.getElementsByTagName("li");
if(e.length){l=0;for(m=e.length;l<m;l++){j=e[l];j.onmouseover=function(){addClass(this,"current")};j.onmouseout=function(){removeClass(this,"current")};j.childNodes[1].childNodes[0].onclick=function(){var e=this.parentNode.parentNode;g.del(a(e.childNodes[0].childNodes[0]));e.parentNode.removeChild(e);b();d();st_get(this,"dh.chaxun.historyclear",0);return false};j.childNodes[0].childNodes[0].onclick=function(){g.add(a(this));st_get(this,"dh.chaxun.historyclick",0);return true}}addListener(p.childNodes[1].childNodes[0],
"click",function(){g.clear();p.innerHTML="";b();d();st_get(this,"dh.chaxun.historyclear",0)})}p.style.display="block"}function d(){n=setTimeout(function(){r=0;removeClass(h,"meUsecur");p.style.display="none"},300)}function e(){clearTimeout(n);if(!r){r=1;b()}}for(var f="::",g=new History("recentUsed",10),j=$("mainArea").getElementsByTagName("a"),l=0,m=j.length;l<m;++l)j[l].onclick=function(){g.add(a(this));st_get(this,"dh.chaxun.appclick",0);return true};var h=$("recentChs"),p=$("recentChsBox"),n,
r;addListener(h,"mouseover",e);addListener(h,"mouseout",d);addListener(p,"mouseover",e);addListener(p,"mouseout",d);new TabView({tabTagName:"li",currentClassName:"current",container:$("navTab"),tabPanels:findDownTags($("mainArea"),"div")})})();var g_Get=readGet(),userController=new UserController({cookie:new Cookie});userController.loadBasicInfo();new SoSo_SmartBox("soso_input",function(){$("mycid").value="dh.chaxun.so";$("mainSoso").submit();$("mycid").value="dh.chaxun.smart";return true},function(){return true});
new installHint($("soso_input"),"请输入关键词",200);function setHomeEventHandler(a){setHomepage(location.protocol+"//"+location.host);stopBubble(a);return false}addListener($("setHomeLink"),"click",function(a){st_get(this,"u01.func.homepage",0);setHomeEventHandler(a)});addListener($("setHome"),"click",function(a){st_get(this,"u01.func.homepage",1);setHomeEventHandler(a)});addListener($("haoLogo"),"click",function(a){st_get(this,"u01.func.homepage",2);setHomeEventHandler(a)});
setTimeout(function(){$("soso_input").focus()},0);installStat();
