document.domain=window.location.host.substring(window.location.host.indexOf(".")+1);var $=function(a){return document.getElementById(a)};String.prototype.truncate_cn=function(a,b){return this.length<=a?this:this.substring(0,a)+(b||"..")};String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")};String.prototype.escapeHTML=function(){return this.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\ /g,"&nbsp;")};
function jsLoader(a,b,d){if("undefined"==typeof d||null==d)d="jsonstring";var e="var_"+(new Date).getTime().toString().substring(7)+parseInt(1E4*Math.random()),a=a+((-1==a.indexOf("?")?"?":"")+"&v="+e),f=document.createElement("script");f.setAttribute("type","text/javascript");f.setAttribute("src",a);var h=document.getElementsByTagName("head")[0];f.onload=f.onreadystatechange=function(){if(!f.readyState||"loaded"==f.readyState||"complete"==f.readyState)if(!("undefined"==typeof window[e]||null==window[e])){if("jsonstring"==
d){var a=eval("("+window[e]+")");"function"==typeof b&&b(a)}else"function"==typeof b&&b(window[e]);try{h.removeChild(f)}catch(j){}e=f=null}};h.appendChild(f)}function addListener(a,b,d){a&&(a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent("on"+b,d))}function getEventTarget(a){a=a||window.event;return a.srcElement||a.target}function stopBubble(a){a=a||window.event;a.preventDefault?(a.preventDefault(),a.stopPropagation()):(a.cancelBubble=!0,a.returnValue=!1)}
function isAncestor(a,b){if(!b||!a)return!1;for(;b!==a&&b!=document.body;)b=b.parentNode;return b===a}function haveClass(a,b){return"undefined"!=typeof a.className&&a.className.match(RegExp("(\\s|^)"+b+"(\\s|$)"))}function addClass(a,b){haveClass(a,b)||(a.className=a.className?a.className+(" "+b):b)}function removeClass(a,b){haveClass(a,b)&&(a.className=a.className.replace(RegExp("(\\s|^)"+b+"(\\s|$)")," "))}function replaceClass(a,b,d){haveClass(a,b)&&(removeClass(a,b),addClass(a,d))}
function get_url_para(a){for(var b=(0<location.search.length?location.search.substring(1):"").split("&"),d,e=0;e<b.length;++e)if(d=b[e].split("="),a==decodeURIComponent(d[0]).toLowerCase())return decodeURIComponent(d[1]);return""}
function readGet(){var a=window.location.href.replace(/&amp;/g,"&").replace(/\#.*$/,""),b={},d;if(-1<a.indexOf("?"))uriArr=a.split("?"),paraStr=uriArr[1];else return b;for(var a=-1<paraStr.indexOf("&")?paraStr.split("&"):Array(paraStr),e=0;e<a.length;e++)try{a[e]=-1<a[e].indexOf("=")?a[e]:a[e]+"=",d=a[e].split("="),b[d[0]]=decodeURIComponent(d[1].replace(/\+/g," ")).escapeHTML()}catch(f){}return b}var g_Get=readGet(),util={};util.readGet=readGet;util.jsLoader=jsLoader;
function gotoHelp(){window.open("/sethelp")}function setHomepage(a){st_get(this,"u01.func.homepage",0);if(document.all)try{document.body.style.behavior="url(#default#homepage)",document.body.setHomePage(a)}catch(b){gotoHelp()}else gotoHelp()}function addAsFavorite(a,b){st_get(this,"u01.func.addfav",0);try{if(window.sidebar)window.sidebar.addPanel(a,b,"");else if(document.all)window.external.AddFavorite(b,a);else return gotoHelp(),!0}catch(d){gotoHelp()}}
function pr_getdt1(a,b,d,e){var f=document,h="-",g=(new Date).getUTCMilliseconds(),j=f.cookie.match(/suid=([^;]*)(;|$)/);j?h=j[1]:(f.cookie="suid="+Math.round(2147483647*Math.random())*g%1E10+";path=/; domain=soso.com;expires=Sun, 18 Jan 2038 00:00:00 GMT;",(j=f.cookie.match(/suid=([^;]*)(;|$)/))&&(h=j[1]));e=e||"";(new Image(1,1)).src="http://pr.soso.com/pingd?srctype=getsret&ourl="+escape(a)+"&lurl="+escape(f.location)+"&suid="+h+"&ch="+b+"&sort="+d+"&sc="+e+"&rand="+Math.random()}
function pr_get(a,b,d,e){0==a.length||0==b.length||pr_getdt1(a,b,d,e)}function st_get(a,b,d){var e=g_Get.cid;e&&"u01"!=e&&b.replace(/^u01\./,"u01."+e);setTimeout(function(){"object"==typeof __sosostat&&"function"==typeof __sosostat.prget&&__sosostat.prget(a,b.trim()+"."+d,0,"daoh")},0)}
function installStat(){for(var a=document.body.getElementsByTagName("*"),b=a.length,d=0;d<b;++d){var e=a[d].getAttribute("st_get");e&&function(b){addListener(a[d],"click",function(){st_get(this,b,0)})}(e);if(e=a[d].getAttribute("st_get_group"))for(var f=a[d].getElementsByTagName("a"),h=0;h<f.length;++h)(function(a,b){addListener(f[h],"click",function(){st_get(this,a,b)})})(e,h)}}
function Cookie(){this.get=function(a){return(a=document.cookie.match(RegExp("(^| )"+a+"=([^;]*)(;|$)")))?unescape(a[2]):null};this.getNotExpireTime=function(){var a=new Date;a.setTime(a.getTime()+31536E6);return a.toGMTString()};this.set=function(a,b,d,e,f){document.cookie=a+"="+escape(b)+"; expires="+(d?d:this.getNotExpireTime())+";path="+(e?e:"/")+"; domain=."+(f?f:window.location.host)};this.del=function(a,b){document.cookie=a+"=;path="+(b?b:"/")+";domain="+document.domain+";expires="+(new Date("1970/1/1")).toGMTString()}}
function PageMask(a){this.open=function(){a.style.display="block";a.style.width=document.body.clientWidth+"px";a.style.height=document.body.clientHeight+"px"};this.close=function(){a.style.display="none"}}
function Ptlogin2(){this.open=function(a,b,d){a&&(d&&d.open(),window.ptlogin2_onResize=function(e,d){a.style.width=e+"px";a.style.height=d+"px";b.style.top=(document.documentElement.clientHeight-d)/2+"px";b.style.left=(document.documentElement.clientWidth-e)/2+"px";b.style.visibility="visible"},window.ptlogin2_onClose=function(){b.style.display="none";d&&d.close()},b.style.display="block",b.style.visibility="hidden",a.src="http://ui.ptlogin2."+document.domain+"/cgi-bin/login?appid=50000201&s_url="+
encodeURIComponent(location.href)+"&f_url=loginerroralert&target=parent&link_target=blank&low_login=1&random="+Math.random())}}
function User(){function a(a){a&&(d=!0);_obj.loginType=a.loginType;_obj.nick=a.nick;"function"===typeof b&&b(_obj)}var b,d=!1;this.isLogin=function(){return d};this.login=function(d){b=d;_obj=this;window.loginInfoCallback=a;jsLoader("http://newdata.qq.com/newLoginFull.q?callback=loginInfoCallback")};this.logout=function(a){for(var b="uin,skey,luin,lskey,__nick,__face".split(","),d=0;d<b.length;++d)a.del(b[d]);location.reload();return!1}}
(function(a,b,d){function e(){F.style.display="none";J.style.display="none";q=r.get("uin");s=r.get("luin");y=r.get("skey");z=r.get("lskey");q&&(q=q.replace(/^o0*/,""));s&&(s=s.replace(/^o0*/,""));q=q?q:"";v("uin",q);y=y?y:"";v("skey",y);s=s?s:"";v("luin",s);z=z?z:"";v("lskey",z);A(G+"navedSite.php?"+o[t]("&"))}function f(){K.style.display="none";L||(F.style.display="block",$("noLoginQQ").innerHTML=l)}function h(b){if(b&&b.r){var d=b.expireat;"function"==typeof C&&C(b);b.daily||H(b.r,function(){v("x",
w(b.r))("y",w(b.s))("hs",a[k])("ss",a[m]);A(G+"navi.php?callback=avFinishCallback&"+o[t]("&"));r.set(I,1,d)})}}function g(a){a&&"function"==typeof D&&D(a)}function j(a){for(var b=[],d=(1<<u)-1,e=0,f=a.length;e<f*u;e+=u)b[e>>5]|=(a.charCodeAt(e/u)&d)<<e%32;return b}function n(a){for(var b=x?"0123456789ABCDEF":"0123456789abcdef",d="",e=0,f=a.length;e<4*f;e++)d+=b.charAt(a[e>>2]>>8*(e%4)+4&15)+b.charAt(a[e>>2]>>8*(e%4)&15);return d}var l=util.readGet().uin,k="haosign",m="sososign",o=[],p={},x=0,t="join",
A=util.jsLoader,w=encodeURIComponent,E=Math,B=cd="concat",u=8,v=function(a,b){return a in p?v:(p[a]=!0,o=o[B](a[cd]("=",b)),v)},C,D,r=new Cookie,I="navedDaily",G="http://faxin.soso.com/",K=$("tipLogin"),F=$("tipNoLogin"),J=$("tipErrQQ"),L=r.get(I),q=r.get("uin"),y=r.get("skey"),s=r.get("luin"),z=r.get("lskey"),H=function(b,d){if(!a[k])return setTimeout(function(){H(b,d)},50),!1;var e=q||s;a[m]=n(j(w(a.__nick||"nologin")+"|"+e+"|"+b)).split("").reverse()[t]("");d()};a[b]=function(o,p){return C=o,D=
p,a[b+"FinishCallback"]=g,a[b+"Callback"]=h,d.onmousemove=function(b){var b=b||event,e=[],f=q||s;d.onmousemove=null;for(var b=j([w(a.__nick||"nologin"),b.type,b.pageX||b.clientX,f,b.pageY||b.clientY][t]("|")),f=[],g=0,h=b.length;g<h;g++)e[g]=g;e.sort(function(){return 5*E.random()-1});f.push(e[t]("_"));for(g=0;g<h;g++)f.push(b[e[g]]);a[k]=f[t](",")},{login:e,nologin:f}}})(window,"av",document);
var wea_to_icon_map={"晴":0,"多云":1,"阴":2,"阵雨":3,"雷阵雨":4,"雷阵雨并伴有冰雹":5,"雨夹雪":6,"小雨":7,"中雨":8,"大雨":9,"暴雨":10,"大暴雨":11,"特大暴雨":12,"阵雪":13,"小雪":14,"中雪":15,"大雪":16,"暴雪":17,"雾":18,"冻雨":19,"沙尘暴":20,"小雨-中雨":21,"中雨-大雨":22,"大雨-暴雨":23,"暴雨-大暴雨":24,"大暴雨-特大暴雨":25,"小雪-中雪":26,"中雪-大雪":27,"大雪-暴雪":28,"浮尘":29,"扬沙":30,"强沙尘暴":31,"大风":32,"龙卷风":33};
function Observable(){var a={};this.addEventListener=function(b,d){if("function"!=typeof d)return!1;"undefined"==typeof a[b]&&(a[b]=[]);for(var e=0;e<a[b].length;++e)if(a[b][e]==d)return!1;a[b].push(d);return!0};this.removeEventListener=function(b,d){if("undefined"==typeof a[b])return!1;for(var e=0;e<a[b].length;++e)if(a[b][e]==d)return a[b].splice(e,1),!0;return!1};this.notify=function(b,d){if(a[b])for(var e=0;e<a[b].length;++e)if("function"==typeof a[b][e])a[b][e](d)}}
function Weather(){var a=new Observable,b={};this.addEventListener=function(b,e){return a.addEventListener(b,e)};this.removeEventListener=function(b,e){return a.removeEventListener(b,e)};this.getWeather=function(a){"undefined"!=typeof b[a]?showWeather(b[a]):jsLoader("http://sou.qq.com/online/get_weather.php?callback=showWeather"+(a?"&city="+encodeURIComponent(a):""))};window.showWeather=function(d){d.future&&d.future.name&&(b[d.future.name]=d);a.notify("wea_data_ready",d)}}
function Tab(){function a(a){if(e){var d=$("addTabBtn"),f=document.createElement("li");f.innerHTML='<a href="#">'+a+'</a><span class="close"></span>';e.insertBefore(f,d.parentNode);b.length==g&&addClass(e,"noadd");2==b.length&&removeClass(e,"noclose")}}var b=[],d=-1,e=$("cityTab"),f=new Observable,h=this,g=3;this.init=function(d){if(!d||0==d.length)return!1;b=d;for(d=0;d<b.length;++d)a(b[d]);1>=b.length&&addClass(e,"noclose");removeClass(e,"hidden")};this.setSelect=function(a,b){var g=e.getElementsByTagName("li"),
a=0>a?g.length-1+a:a;if(b||a!==d){for(var h=0;h<g.length-1;++h)h===a?(addClass(g[h],"current"),d=a):removeClass(g[h],"current");f.notify("click_tab",{index:a})}};this.addTab=function(d){for(var e=0;e<b.length;++e)if(b[e]===d)return!1;b.push(d);return a(d)};this.addEventListener=function(a,b){return f.addEventListener(a,b)};this.getTabList=function(){return b};this.getTabNumber=function(){return b.length};this.getTabLabel=function(a){return b[a]};addListener(e,"click",function(a){stopBubble(a);for(var n=
a=getEventTarget(a);n!=document.body&&"LI"!=n.tagName;)n=n.parentNode;if(n===document.body)return!1;for(var l=e.getElementsByTagName("li"),k=0;k<l.length;++k)if(l[k]===n)if(k==l.length-1)f.notify("new_tab");else if("SPAN"==a.tagName){var m=k;if(1>=h.getTabNumber())f.notify("close_tab",{error:"1"});else{var o=b[m],p=e.getElementsByTagName("li");e.removeChild(p[m]);b.splice(m,1);b.length==g-1&&removeClass(e,"noadd");1==b.length&&addClass(e,"noclose");d>=m&&d--;h.setSelect(d,!0);f.notify("close_tab",
{index:m,name:o})}}else h.setSelect(k);return!1})}function handleWD(a){return a.replace("无风向","无持续风向")}function get_wea_img_url(a,b){var d=0;"undefined"!=typeof wea_to_icon_map[a]&&(d=wea_to_icon_map[a]);return"/images/wea2/"+(b&&2>d?"s_b"+d+".jpg":"s_a"+d+".jpg")}
function showToday(a){$("bwea").innerHTML=a.BWEA;$("ewea").innerHTML=a.EWEA;$("bwd").innerHTML=handleWD(a.BWD)+" "+a.BWS;$("ewd").innerHTML=handleWD(a.EWD)+" "+a.EWS;$("bwea_img").src=get_wea_img_url(a.BWEA);$("ewea_img").src=get_wea_img_url(a.EWEA,!0);$("tmax").innerHTML=a.TMAX+"°C";$("tmin").innerHTML=a.TMIN+"°C"}
function showFutureWea(a,b){if(a&&b){var d=a.getElementsByTagName("img");d&&2==d.length&&(d[0].src=get_wea_img_url(b.BWEA),d[1].src=get_wea_img_url(b.EWEA,!0));if(d=a.getElementsByTagName("span"))d[3].innerHTML=b.BWEA==b.EWEA?b.BWEA:b.BWEA+"转"+b.EWEA,d[4].innerHTML=(b.TMIN==b.TMAX?b.TMIN:b.TMIN+"~"+b.TMAX)+"°C",d[5].innerHTML=handleWD(b.BWD)+" "+b.BWS}}
function showForecast(a){if(a){showToday(a[0]);var b=$("futureArea");if(b)for(var b=b.getElementsByTagName("div"),d=0,e=0;d<b.length;++d)e<a.length-1&&haveClass(b[d],"section")&&showFutureWea(b[d],a[e++])}}
function showZhishu(a){if(a){var b="CT_N,CT,PL_N,PL,CO_N,CO,CL_N,CL,GM_N,GM,GJ_N,GJ,XC_N,XC,UV_N,UV".split(",");if($("zhishuArea"))for(var d=$("zhishuArea").getElementsByTagName("span"),e=0;e<b.length&&e<d.length;++e)40<a[b[e]].length&&(d[e].title=a[b[e]],a[b[e]]=a[b[e]].substring(0,37)+"..."),d[e].innerHTML=a[b[e]]}}function showTemperature(a){"undefined"!=typeof a&&$("temperature")&&($("temperature").innerHTML=a+"°C")}var g_wea_cache={},g_cur_selected_city="",g_citys=[];
function saveCache(a,b){g_wea_cache[a]=b;g_cur_selected_city||(g_cur_selected_city=a)}function getCache(a){return g_wea_cache[a]}function getCurCity(){return g_cur_city}function _showWeather(a){showCityWeather(a)}function showCityWeather(a){a.real&&showTemperature(a.real.temperature);a.future&&showForecast(a.future.forecast);showZhishu(a.future.zhishu);removeClass($("todayArea"),"hidden");removeClass($("futureArea"),"hidden")}
function updateDate(){for(var a=new Date,b=0;5>b;++b)$("date"+b).innerHTML="（"+(a.getMonth()+1)+"月"+a.getDate()+"日）",a.setTime(a.getTime()+864E5);b="日,一,二,三,四,五,六".split(",");$("weekday0").innerHTML="周"+b[(a.getDay()+5)%7];$("weekday1").innerHTML="周"+b[(a.getDay()+6)%7]}function updateHuangli(a){a.goodbad&&updateGoodBad(a.goodbad);a.star&&updateStar(a.star)}
function updateGoodBad(a){$("lunarYear").innerHTML="壬辰(龙)年";$("lunarDate").innerHTML=a.lunar;20<a.good.length&&($("goodThing").title=a.good,a.good=a.good.truncate_cn(20));$("goodThing").innerHTML=a.good;20<a.bad.length&&($("badThing").title=a.bad,a.bad=a.bad.truncate_cn(20));$("badThing").innerHTML=a.bad;$("chongThing").innerHTML="生宵"+a.chong.replace(/\(.*\)/," ")}function updateStar(a){a&&(g_star=a,changeStar(g_select_star))}
function changeStar(a){for(var b=0;b<g_star.length;++b)if(g_star[b].star===a)return showStar(g_star[b]);return showStar(g_star[0])}
function showStar(a){$("currentStar").innerHTML=a.star;$("starLuckyNum").innerHTML=a.shuzi;$("starLuckyColor").innerHTML=a.yanse;75<a.gaishu.length&&($("starGaishu").title=a.gaishu,a.gaishu=a.gaishu.truncate_cn(75,"..."));$("starGaishu").innerHTML=a.gaishu;var b=parseInt(a.zonghe.replace("%",""));isNaN(b)&&(b=100);b=parseInt(b/20)+1;b=1>b?1:b;b=5<b?5:b;$("starLevel").className="star s"+b;g_cookie.set("starsel",a.star)}var g_star=null;jsLoader("http://sou.qq.com/online/get_huangli.php");
function updateSOSOTop(a){for(var b=$("sosoTopList").getElementsByTagName("a"),d=0;d<a.length&&d<b.length;++d)b[d].innerHTML=a[d]}jsLoader("http://sou.qq.com/online/get_sosotop.php?r="+Math.random());
function SearchBox(a){function b(a){if(g)for(key in a)if(a[key]){for(var b=g.getElementsByTagName("input"),d=!1,e=0;e<b.length;++e)if(b[e].name.trim()==key.trim()){b[e].value=a[key];d=!0;break}d||(b=document.createElement("input"),b.type="hidden",b.name=key,b.value=a[key],g.appendChild(b))}}function d(a){if(g)for(;g.firstChild;)g.removeChild(g.firstChild);b(a.hiddeninputs);b(n);l="function"===typeof a.beforesubmit?a.beforesubmit:null;j.acceptCharset="undefined"!=typeof a.acceptCharset?a.acceptCharset:
"GBK";j.action=a.action}function e(a){if(""==f.value.trim()||!haveClass(f,"onfocus"))return stopBubble(a),f.focus(),!1;"function"==typeof m&&m();return"function"===typeof l&&!l(f.value.trim())?(stopBubble(a),!1):!0}var f=a.input,h=a.tabBox,g=a.hiddenParamsDiv,j=a.form,n=a.sourcePara,l=null;if(f){var k=[{action:"http://soso.qq.com/q",hiddeninputs:{bid:"306"}},{action:"http://image.soso.com/image.cgi",hiddeninputs:{sc:"img"}},{action:"http://video.soso.com/search/"},{action:"http://cgi.music.soso.com/fcgi-bin/m.q"},
{action:"http://wenwen.soso.com/z/Search.e",acceptCharset:"UTF-8",beforesubmit:function(a){a:{for(var a="S"+a+"\ufeff",b=g.getElementsByTagName("input"),d=0;d<b.length;++d)if("sp"==b[d].name){b[d].value=a;break a}b=document.createElement("input");b.type="hidden";b.name="sp";b.value=a;g.appendChild(b)}return!0},hiddeninputs:{ch:"w.search.sb"}},{action:"http://news.soso.com/n.q",hiddeninputs:{ty:"c"}},{action:"http://map.soso.com/?pid=haoqq.map"}],m=function(){"undefined"!=typeof g_user&&g_user.isLogin()&&
b({cid:n.cid+".q"})};(function(){a.button&&(a.button.onclick=function(a){e(a)&&j.submit();return!1});addListener(j,"submit",e);if(h){for(var b=h.getElementsByTagName("span"),f=0;f<b.length;++f)(function(a,b){addListener(a,"click",function(){if(!(!h||!a||a.className&&a.className=="currentTab"))for(var f=h.getElementsByTagName("span"),g=0;g<f.length;++g)f[g].className=f[g]===a?"currentTab":"";d(b);e()===true&&j.submit()});addListener(a,"mouseover",function(b){haveClass(a,"currentTab")||addClass(a,"hover");
stopBubble(b)});addListener(a,"mouseout",function(){haveClass(a,"currentTab")||removeClass(a,"hover")})})(b[f],k[f]);d(k[0])}})()}}function installHint(a,b,d,e,f){function h(){this.onfocus=null;haveClass(a,e)||(a.value="");addClass(a,e);"function"==typeof f&&f();this.blurtmo&&(clearTimeout(this.blurtmo),this.blurtmo=null)}function g(){e=e||"onfocus";a.value=b;removeClass(a,e)}a&&b&&(a.onblur=function(){a.onfocus=h;""==a.value&&(d?this.blurtmo=setTimeout(g,d):g())},a.onfocus=h,g())}
var calendar={lunarInfo:[19416,19168,42352,21717,53856,55632,91476,22176,39632,21970,19168,42422,42192,53840,119381,46400,54944,44450,38320,84343,18800,42160,46261,27216,27968,109396,11104,38256,21234,18800,25958,54432,59984,28309,23248,11104,100067,37600,116951,51536,54432,120998,46416,22176,107956,9680,37584,53938,43344,46423,27808,46416,86869,19872,42448,83315,21200,43432,59728,27296,44710,43856,19296,43748,42352,21088,62051,55632,23383,22176,38608,19925,19152,42192,54484,53840,54616,46400,46496,
103846,38320,18864,43380,42160,45690,27216,27968,44870,43872,38256,19189,18800,25776,29859,59984,27480,21952,43872,38613,37600,51552,55636,54432,55888,30034,22176,43959,9680,37584,51893,43344,46240,47780,44368,21977,19360,42416,86390,21168,43312,31060,27296,44368,23378,19296,42726,42208,53856,60005,54576,23200,30371,38608,19415,19152,42192,118966,53840,54560,56645,46496,22224,21938,18864,42359,42160,43600,111189,27936,44448],lunarMonth:"正,二,三,四,五,六,七,八,九,十,十一,腊".split(","),monthPrefix:["初","十","廿",
"三"],lunarDay:"十,一,二,三,四,五,六,七,八,九".split(","),lYearDays:function(a){var b,d=348;for(b=32768;8<b;b>>=1)d+=this.lunarInfo[a-1900]&b?1:0;return d+this.leapDays(a)},leapDays:function(a){return this.leapMonth(a)?this.lunarInfo[a-1900]&65536?30:29:0},leapMonth:function(a){return this.lunarInfo[a-1900]&15},monthDays:function(a,b){return this.lunarInfo[a-1900]&65536>>b?30:29},Lunar:function(a){var b=0,d=0,e=Math.floor((a-new Date(1900,0,31))/864E5);this.dayCyl=e+40;this.monCyl=14;for(a=1900;2050>a&&0<e;a++)d=
this.lYearDays(a),e-=d,this.monCyl+=12;0>e&&(e+=d,a--,this.monCyl-=12);this.year=a;this.yearCyl=a-1864;b=this.leapMonth(a);this.isLeap=!1;for(a=1;13>a&&0<e;a++)0<b&&a==b+1&&!1==this.isLeap?(--a,this.isLeap=!0,d=this.leapDays(this.year)):d=this.monthDays(this.year,a),!0==this.isLeap&&a==b+1&&(this.isLeap=!1),e-=d,!1==this.isLeap&&this.monCyl++;0==e&&0<b&&a==b+1&&(this.isLeap?this.isLeap=!1:(this.isLeap=!0,--a,--this.monCyl));0>e&&(e+=d,--a,--this.monCyl);this.month=a;this.day=e+1}};
function showDate(){var a=new Date,b=a.getFullYear(),d=a.getMonth()+1,e=a.getDate(),f=a.getDay(),h=a.getMinutes(),g=a.getHours(),d=(10>d?"0":"")+d,e=(10>e?"0":"")+e,h=(10>h?"0":"")+h,g=(10>g?"0":"")+g;calendar.Lunar(a);a="";calendar.isLeap&&(a="闰");a+=calendar.lunarMonth[calendar.month-1]+"月";a=20!=calendar.day?a+calendar.monthPrefix[10>=calendar.day?0:Math.floor(calendar.day/10)]:a+"二";a+=calendar.lunarDay[Math.floor(calendar.day%10)];$("date_of_today").innerHTML=b+"年"+d+"月"+e+"日 周"+"日,一,二,三,四,五,六".split(",")[f]+
"（农历"+a+"）";$("real_time").innerHTML=g+":"+h;setInterval(function(){var a=new Date;0==a.getSeconds()&&(g=a.getHours(),h=a.getMinutes(),h=(10>h?"0":"")+h,g=(10>g?"0":"")+g,$("real_time").innerHTML=g+":"+h)},1E3)}
function SoSo_SmartBox(a,b,d){var e=this,f="object"==typeof a?a:document.getElementById(a),h=!1,g=-1,j=[],n=[],l="",k=null,m=!1,o=function(){for(pos in j)j[pos].className="mouseout"},p=function(a){return"string"==typeof a?a.replace(/^\s\s*/,"").replace(/\s\s*$/,""):""},x=p(f.value),t=function(){"function"==typeof b&&b()},A=function(){m=!1;g=-1;j=[];n=[];l="";var a=document.getElementById(0);a&&null!=a&&a.parentNode.removeChild(a)},w="soso_jpcall_"+Math.round(1E6+1E7*Math.random());eval(w+"=function(d){soso_jpcall_inner(d);}");
var E=util.jsLoader,B=function(){if("请输入关键词"!=f.value){soso_global_smartbox_data=[];h=!1;var a="http://www.soso.com/smart.q?w="+encodeURIComponent(f.value)+"&m="+w+"&_"+Math.random();E(a)}},u=function(){null!=k&&(clearTimeout(k),k=null);k=setTimeout(function(){!h||p(f.value).length==0?A():d()&&l!=f.value&&B();k=null},300)};(function(){e.Event.add(f,"keypress",function(a){if(!m&&(38==a.keyCode||40==a.keyCode))h=!0,u();0!=j.length&&13==a.keyCode&&-1!=g&&(e.Event.stop(a),x=f.value,t())});e.Event.add(f,
"keyup",function(a){if(!m&&(38==a.keyCode||40==a.keyCode))h=!0,u();0!=j.length&&(13==a.keyCode&&-1!=g?(e.Event.stop(a),x=f.value,t()):38==a.keyCode?(e.Event.stop(a),o(),g=0>g?j.length-1:g-1,-1==g?l=f.value="":(j[g].className="mouseover",l=f.value=n[g].word)):40==a.keyCode?(e.Event.stop(a),o(),g=g>j.length-1?0:g+1,g==j.length?l=f.value="":(j[g].className="mouseover",l=f.value=n[g].word)):27==a.keyCode&&(e.Event.stop(a),o(),A(),f.value=""))});e.Event.add(f,"blur",function(){h=!1;u()});e.Event.add(window,
"resize",function(){h&&B()});var a,b=function(){a=setTimeout(function(){x!=p(f.value)&&(x=p(f.value),h=!0,u());a=setTimeout(arguments.callee,80)},80)};e.Event.add(f,"focus",function(){b()});e.Event.add(f,"blur",function(){clearTimeout(a)})})()}
SoSo_SmartBox.prototype.Event={add:function(a,b,d){a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent("on"+b,d)},remove:function(a,b,d){a.removeEventListener?a.removeEventListener(b,d,!1):a.detachEvent("on"+b,d)},stop:function(a){a.preventDefault?(a.preventDefault(),a.stopPropagation()):(a.cancelBubble=!0,a.returnValue=!1)}};
